# Generated by Django 4.2.2 on 2023-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_source", "0001_note_and_tag_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="deleted_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
